### Input
# input rgba image path (default to None, can be load in GUI too)
input: 
negative_prompt: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"
# input mesh for stage 2 (auto-search from stage 1 output path if None)
mesh:
# estimated elevation angle for input image 
elevation: 0
# reference image resolution
ref_size: 256
# density thresh for mesh extraction
density_thresh: 1
# stage
stage: "LGM"

### Output
outdir: logs
mesh_format: obj
save_path: ???

### Training
# use mvdream instead of sd 2.1
mvdream: False
# use imagedream
imagedream: True
# use stable-zero123 instead of zero123-xl
stable_zero123: False 
# guidance loss weights (0 to disable)
lambda_sd: 0.0
lambda_zero123: 0
# warmup rgb supervision for image-to-3d
warmup_rgb_loss: True
# training batch size per iter
batch_size: 1
# training iterations for stage 1
iters: 500
# whether to linearly anneal timestep
anneal_timestep: True
# training iterations for stage 2
iters_refine: 50
# training camera radius
radius: 1.5
# training camera fovy
fovy: 49.1
# training camera min elevation
min_ver: -30
# training camera max elevation
max_ver: 30
# checkpoint to load for stage 1 (should be a ply file)
load:
# whether allow geom training in stage 2
train_geo: False
# prob to invert background color during training (0 = always black, 1 = always white)
invert_bg_prob: 0.0

### GUI
gui: False
force_cuda_rast: False
# GUI resolution
H: 512
W: 512

### general settings
workspace_name: ""

### mvdrag
prompt: "a martin boot"
prompt_edit: "a martin boot"
drag_points_path_occ: "/mnt/slurm_home/hhchen/LGM/martin_boot_noscale/test_mvdream_0_line.txt"
drag_points_path_all: "/mnt/slurm_home/hhchen/LGM/martin_boot_noscale/test_mvdream_0_line.txt"
image_path: "/mnt/slurm_home/hhchen/LGM/martin_boot_noscale/test_mvdream_0.png"
masks_path: "/mnt/slurm_home/hhchen/LGM/martin_boot_noscale/test_mvdream_0_comb_mask.png"
edit_masks_path:
mvdream_path: "/mnt/slurm_home/hhchen/dreamgaussian/mvdream_diffusers/mvdream-sd21-diffusers"
num_steps: 150
scale: 1.0
guidance_scale: 4.0
SDE_strength: 1.0
w_edit: 4.0
w_content: 10.0

### LGM
resume: "LGM/pretrained/model_fp16_fixrot.safetensors"
src_points_path: "/mnt/slurm_home/hhchen/APAP/data/apap_3d/processed/tree_sparow/keypoints/0002/srcs_single_keypoints.txt"
tgt_points_path: "/mnt/slurm_home/hhchen/APAP/data/apap_3d/processed/tree_sparow/keypoints/0002/user_single_keypoints.txt"

### Gaussian splatting
optimize_gaussians: False
mlp_others: False
num_pts: 5000
sh_degree: 0
position_lr_init: 0.001
position_lr_final: 0.00002
position_lr_delay_mult: 0.02
position_lr_max_steps: 500
feature_lr: 0.01
opacity_lr: 0.05
scaling_lr: 0.005
rotation_lr: 0.005
percent_dense: 0.1
density_start_iter: 100000
density_end_iter: 10000000
densification_interval: 100
opacity_reset_interval: 100
densify_grad_threshold: 0.01

### Deformation
deformation_lr_init: 0.00064
deformation_lr_final: 0.00064
deformation_lr_delay_mult: 0.01

### Editing accuracy
# pix_pos_path: "/mnt/slurm_home/hhchen/LGM/blue_wolf/blue_wolf_line.txt"

### Textured Mesh
geom_lr: 0.0001
texture_lr: 0.2